name: create-draft-release-with-artifacts

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Run id of the action run to pull artifacts from
        required: true

jobs:
  github-release:
    name: github-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          path: artifacts
          workflow: build-and-test.yml
          run_id: ${{ github.event.inputs.run_id }}

      - name: Package release assets
        run: scripts/package-release-assets.sh

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: manual release ${{ github.event.inputs.run_id }}
          files: release/ouch-*
