name: Automatic trigger draft release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-workflow-build-artifacts-and-run-tests:
    uses: ./.github/workflows/build-artifacts-and-run-tests.yml
    with:
      matrix_all_combinations: true
      upload_artifacts: true

  automated-draft-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: call-workflow-build-artifacts-and-run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          path: artifacts

      - name: Package release assets
        run: scripts/package-release-assets.sh

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: release/ouch-*
